version: "3"
services:
  app:
    build: .
    ports:
      - 8089:80
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_CONFIG: /etc/ngrok.yaml
    restart: unless-stopped
    ports:
    -   8040:4040
    volumes:
    -   ./docker/ngrok.yaml:/etc/ngrok.yaml